package(
    licenses = ["notice"],  # Apache 2.0
)

filegroup(
    name = "cc_files",
    srcs = [
        "//test/core/util:cc_files",
        "//test/core/indexer:cc_files",
        "//test/core/retrieval:cc_files",
        "//test/core/feature:cc_files",
        "//test/core/context:cc_files",
    ],
    visibility = ["//test:__pkg__"],
)
