package(
     licenses = ["notice"],  # Apache 2.0
)

filegroup(
    name = "core_cc_files",
    srcs = [
        "//core/util:cc_files",
        "//core/service:cc_files",
        "//core/recommend:cc_files",
        "//core/indexer:cc_files",
        "//core/retrieval:cc_files",
        "//core/feature:cc_files",
        "//core/context:cc_files",
    ],
    visibility = ["//visibility:public"]
)
