package(
     licenses = ["notice"],  # Apache 2.0
)

filegroup(
    name = "cc_files",
    srcs = ["//pyrec/core/util:cc_files",
            "//pyrec/core/service:cc_files"],
    visibility = ["//pyrec:__pkg__"]
)
